spring:
  application:
    name: resourceapi
  datasource:
    url: "jdbc:mysql://localhost:3306/imagebookdb"
    username: root
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  h2:
    console:
      enabled: true
aws:
  s3:
    service-endpoint: "http://localhost:9090/"
    region: us-east-2
    access-key: "use -Daws.s3.access-key"
    secret-key: "use -Daws.s3.secret-key"
